# 吾爱破解论坛解析配置
# 针对吾爱破解论坛文章的特定规则

title_selector: "#thread_subject"
content_selector: "#postlist"

# 需要排除的元素CSS选择器
exclude_selectors:
  - "script"
  - "style"
  - ".advertisement"
  - ".ad"
  - ".banner"
  - ".related_read"
  - ".post_bubble"
  - ".post_copyright"
  - ".post_ratings"
  - ".post_tags"
  - ".post_attachlist"
  - ".post_relate_thread"
  - ".post_editor"
  - ".pagination"
  - ".footer"
  - ".header"
  - ".nav"
  - ".sidebar"
  - ".thread_tools"
  - ".thread_author"
  - ".thread_meta"
  - ".post_author"
  - ".post_meta"
  - ".post_edit"
  - ".post_delete"
  - ".post_report"
  - ".post_quote"
