# 恩山无线论坛解析配置
# 针对恩山无线论坛文章的特定规则

title_selector: "h1#thread_subject"
content_selector: "div#postlist"

# 需要排除的元素CSS选择器
exclude_selectors:
  - "script"
  - "style"
  - ".advertisement"
  - ".ad"
  - ".banner"
  - ".related_threads"
  - ".thread_tools"
  - ".thread_author"
  - ".thread_meta"
  - ".post_author"
  - ".post_meta"
  - ".post_ratings"
  - ".post_tags"
  - ".post_attachlist"
  - ".post_edit"
  - ".post_delete"
  - ".post_report"
  - ".post_quote"
  - ".pagination"
  - ".footer"
  - ".header"
  - ".nav"
  - ".sidebar"
  - ".post_bubble"
  - ".post_copyright"
  - ".post_relate_thread"
  - ".post_editor"
  - ".post_like"
  - ".post_comment"
