# CSDN网站解析配置
# 针对CSDN文章的特定规则

title_selector: "#articleContentId"
content_selector: "#content_views"

# 需要排除的元素CSS选择器
exclude_selectors:
  - "script"
  - "style"
  - ".advertisement"
  - ".ad"
  - ".banner"
  - ".header"
  - ".nav"
  - ".sidebar"
  - ".footer"
  - ".article-title-box"
  - ".article-bar-top"
  - ".article-info-box"
  - ".article-tags-box"
  - ".article-copyright"
  - ".article-footer-tag"
  - ".recommend-box"
  - ".aside-content"
  - ".comment-box"
  - ".comment-form"
  - ".comment-list"
  - ".pagination"
  - ".tool-box"
  - ".article-like"
  - ".article-collect"
  - ".article-share"
  - ".article-comment"
  - ".article-edit"
  - ".article-delete"
  - ".article-report"
  - ".article-copy"
  - ".article-stats"
  - ".article-views"
  - ".article-collections"
  - ".article-comments"
  - ".article-likes"
  - ".related-articles"
  - ".recommended-articles"
  - ".article-source-link"
  - ".article-author-info"
  - ".article-author-name"
  - ".article-author-avatar"
  - ".article-author-follow"
