# 东方财富网解析配置
# 针对东方财富网文章页面的特定规则

title_selector: ".newsTitle, h1"
content_selector: ".newsContent, .article-body"

# 需要排除的元素CSS选择器
exclude_selectors:
  - "script"
  - "style"
  - "nav"
  - "footer"
  - "header"
  - ".advertisement"
  - ".ad"
  - ".banner"
  - ".popup"
  - ".modal"
  - ".cookie-banner"
  - ".notification"
  - ".sidebar"
  - ".aside"
  - ".related-posts"
  - ".comments"
  - ".comment-section"
  - ".header-bar"
  - ".footer-bar"
  - ".newsHeader"
  - ".articleHeader"
  - ".newsInfo"
  - ".articleInfo"
  - ".newsSource"
  - ".sourceName"
  - ".publishTime"
  - ".viewCount"
  - ".likeCount"
  - ".commentCount"
  - ".shareCount"
  - ".newsActions"
  - ".articleActions"
  - ".actionButton"
  - ".likeButton"
  - ".commentButton"
  - ".shareButton"
  - ".collectButton"
  - ".reportButton"
  - ".newsTags"
  - ".articleTags"
  - ".tagItem"
  - ".relatedNews"
  - ".relatedArticle"
  - ".recommendedNews"
  - ".recommendedArticle"
  - ".newsAd"
  - ".articleAd"
  - ".adUnit"
  - ".subscribeCTA"
  - ".appDownload"
  - ".downloadButton"
  - ".qrCode"
  - ".siteNavigation"
  - ".siteFooter"
  - ".searchBox"
  - ".userMenu"
  - ".notificationBell"
  - ".createPost"
  - ".marketQuotes"
  - ".stockList"
  - ".indexList"
  - ".financeData"
  - ".dataCenter"
  - ".analysisTools"
  - ".liveBroadcast"
  - ".videoSection"
