# 掘金网站解析配置
# 针对掘金文章的特定规则

title_selector: ".article-title"
content_selector: ".article-content"

# 需要排除的元素CSS选择器
exclude_selectors:
  - "script"
  - "style"
  - ".advertisement"
  - ".ad"
  - ".banner"
  - ".header"
  - ".nav"
  - ".sidebar"
  - ".footer"
  - ".article-meta"
  - ".article-tags"
  - ".article-author"
  - ".article-actions"
  - ".article-like"
  - ".article-collect"
  - ".article-comment"
  - ".article-share"
  - ".related-articles"
  - ".recommended-articles"
  - ".comments-section"
  - ".comment-form"
  - ".comment-list"
  - ".pagination"
  - ".article-edit"
  - ".article-delete"
  - ".article-report"
  - ".article-copy"
  - ".article-original"
  - ".article-copyright"
  - ".article-license"
  - ".article-stats"
  - ".article-views"
  - ".article-collections"
  - ".article-comments"
  - ".article-likes"
