# TapTap解析配置
# 适用于TapTap游戏页面

title_selector: ".game-title"
content_selector: ".game-intro"

# 需要排除的元素CSS选择器
exclude_selectors:
  - "script"
  - "style"
  - "nav"
  - "footer"
  - "header"
  - ".advertisement"
  - ".ad"
  - ".banner"
  - ".popup"
  - ".modal"
  - ".cookie-banner"
  - ".notification"
  - ".sidebar"
  - ".sidebar-right"
  - ".sidebar-left"
  - ".related-posts"
  - ".comments"
  - ".comment-section"
  - ".game-tools"
  - ".game-share"
  - ".game-recommend"
  - ".game-related"
  - ".download-button"
  - ".game-price"
